### ISSUE TITLE
Does code work for 1D data?

### ISSUE THREAD

**Issue by brando90** [moskomule/anatome#1]
I am using 1D data but I get this error:

```
RuntimeError: CCAHook currently supports tensors of dimension (2, 4), but got 1 instead.
```

why?

**Comment by brando90** [comment]
sample code:

```
import torch
import torch.nn as nn
from anatome import SimilarityHook

from collections import OrderedDict

from pathlib import Path

# get init
path_2_init = Path('~/data/logs/logs_Nov17_13-57-11_jobid_416472.iam-pbs/ckpt_file.pt').expanduser()
ckpt = torch.load(path_2_init)
mdl = ckpt['f']

#
Din, Dout = 1, 1
mdl = nn.Sequential(OrderedDict([
    ('fc1_l1', nn.Linear(Din, Dout)),
    ('out', nn.SELU())
]))


#
hook1 = SimilarityHook(mdl, "fc1_l1")
hook2 = SimilarityHook(mdl, "fc1_l1")
mdl.eval()

#
num_samples_per_task = 5
lb, ub = -1, 1
x = torch.torch.distributions.Uniform(low=lb, high=ub).sample((num_samples_per_task, Din))
with torch.no_grad():
    mdl(x[0])
hook1.distance(hook2, size=8)
```

**Comment by moskomule** [comment]
Hi! Anatome supports 1D data (dimension=2 case). The batch-size dimension is needed to use CCA .

**Comment by brando90** [comment]
> Hi! Anatome supports 1D data (dimension=2 case). The batch-size dimension is needed to use CCA .

ok, thanks, perhaps fixing the tutorial/example might help?

Perhaps a fully contained example like mine would be most helpful too.

**Comment by brando90** [comment]
@moskomule why am I getting really small values? (close to 0?)

I am comparing the same model to itself, so shouldn't the similarity be 1.0ish?

```
import torch
   ...: import torch.nn as nn
   ...: from anatome import SimilarityHook
   ...: 
   ...: from collections import OrderedDict
   ...: 
   ...: from pathlib import Path
   ...: 
   ...: # get init
   ...: path_2_init = Path('~/data/logs/logs_Nov17_13-57-11_jobid_416472.iam-pbs/ckpt_file.pt').expanduser()
   ...: ckpt = torch.load(path_2_init)
   ...: mdl = ckpt['f']
   ...: 
   ...: #
   ...: Din, Dout = 1, 1
   ...: mdl = nn.Sequential(OrderedDict([
   ...:     ('fc1_l1', nn.Linear(Din, Dout)),
   ...:     ('out', nn.SELU())
   ...: ]))
   ...: 
   ...: #
   ...: hook1 = SimilarityHook(mdl, "fc1_l1")
   ...: hook2 = SimilarityHook(mdl, "fc1_l1")
   ...: mdl.eval()
   ...: 
   ...: #
   ...: num_samples_per_task = 100
   ...: lb, ub = -1, 1
   ...: x = torch.torch.distributions.Uniform(low=lb, high=ub).sample((num_samples_per_task, Din))
   ...: with torch.no_grad():
   ...:     mdl(x)
   ...: hook1.distance(hook2, size=8)
   ...: 
Out[43]: 2.384185791015625e-07
```

**Comment by moskomule** [comment]
I will add examples. It’s confusing but the value is distance, I think.

**Comment by brando90** [comment]
> I will add examples. It’s confusing but the value is distance, I think.

how do I feed parameters so that the experiments I run have small errors/variance?

is a large size and a large batch size all I need wrt your library?

**Comment by moskomule** [comment]
Maybe CKA helps: `SimilarityHook(..., cca_distance="lincka")`.

**Comment by brando90** [comment]
> Maybe CKA helps: `SimilarityHook(..., cca_distance="lincka")`.

curious, why do you say that?

Is it not possible with CCA? e.g. I had in mind the

```
iters = 10
num_samples_per_task = 100
size = 8
```

is the larger the better? What are good values you think?

my sample code:

```
#%%


import torch
import torch.nn as nn
from anatome import SimilarityHook

from collections import OrderedDict

from pathlib import Path

# get init
path_2_init = Path('~/data/logs/logs_Nov17_13-57-11_jobid_416472.iam-pbs/ckpt_file.pt').expanduser()
ckpt = torch.load(path_2_init)
mdl = ckpt['f']

#
Din, Dout = 1, 1
mdl = nn.Sequential(OrderedDict([
    ('fc1_l1', nn.Linear(Din, Dout)),
    ('out', nn.SELU())
]))
# mdl.fc1_l1.weight.fill_(2.0)
# mdl.fc1_l1.bias.fill_(2.0)

#
hook1 = SimilarityHook(mdl, "fc1_l1")
hook2 = SimilarityHook(mdl, "fc1_l1")
mdl.eval()

# params for doing "good" CCA
iters = 10
num_samples_per_task = 100
size = 8
# start CCA comparision
lb, ub = -1, 1
with torch.no_grad():
    for _ in range(iters):
        x = torch.torch.distributions.Uniform(low=lb, high=ub).sample((num_samples_per_task, Din))
        mdl(x)
hook1.distance(hook2, size=size)
```

**Comment by brando90** [comment]
also, in the line:

```
        x = torch.torch.distributions.Uniform(low=lb, high=ub).sample((num_samples_per_task, Din))
```

should I really be passing random data or should I be passing real data from my data set?

**Comment by brando90** [comment]
Sorry for the spam, but your example doesn't show how to use your library for what comparing two different models (same architecture and at the same layer).
```
        model = resnet18()
        hook1 = SimilarityHook(model, "layer3.0.conv1")
        hook2 = SimilarityHook(model, "layer3.0.conv2")
        model.eval()
        with torch.no_grad():
            for _ in range(10):
                model(torch.randn(120, 3, 224, 224))
        hook1.distance(hook2, size=8)
```

what I want is something more like this:

```
sim.CCA(mdl1, mdl2, layer)
```

how does one do this correctly with your library?

Thanks in advance for your time!

**Comment by moskomule** [comment]
If I understand correctly, you pass matrices of `Dout x num_samples_per_task = 1 x 500` to CCA (or CKA). `size` is only valid for 4D tensors.

I'm not sure CCA can compare such matrices correctly and stably.

**Comment by brando90** [comment]
> If I understand correctly, you pass matrices of `Dout x num_samples_per_task = 1 x 500` to CCA (or CKA). `size` is only valid for 4D tensors.
> 
> I'm not sure CCA can compare such matrices correctly and stably.

I have control of the `num_samples_per_task `. So I guess I am wondering what number/condition would lower the changes my results are questionable. e.g. if `num_samples_per_task > # weights` for that layer a good heuristic?

**Comment by moskomule** [comment]
Check the papers.
