### ISSUE TITLE
do you preprocess the matrices for us?

### ISSUE THREAD

**Issue by brando90** [moskomule/anatome#12]
I just noticed these two paragraphs from the papers I read and was wondering if you centered the matrices or if the user has to center them for anatome to work before hand.

![Screen Shot 2021-09-15 at 4 31 04 PM](https://user-images.githubusercontent.com/1855278/133512556-be1335c2-dccd-4d8e-8f15-ec973cc209f6.png)
![Screen Shot 2021-09-15 at 4 30 48 PM](https://user-images.githubusercontent.com/1855278/133512559-9419d46f-165e-429b-8d95-2415187406c4.png)

**Comment by moskomule** [comment]
Yes https://github.com/moskomule/anatome/blob/c4c069183aca8aad6f73a4b7ab86f7f7e4ca3d04/anatome/similarity.py#L94

**Comment by brando90** [comment]
> Yes
> 
> https://github.com/moskomule/anatome/blob/c4c069183aca8aad6f73a4b7ab86f7f7e4ca3d04/anatome/similarity.py#L94

Note that function doesn't address what the first paper mentions (which is divide by the frobenius norm too).

So you don't divide by that? If not I am curious why.

Thanks for your replies! I appreciate it.

**Comment by brando90** [comment]
I really do think dividing by frobenius norm is a good idea. E.g. do you really want your similarities to be scale depedent? Since std of vectors/matrices is hard to compute (without considering covariances or whitening) the simplest way to remove scale is to divide by l2 norm (or frobenius for matrices).  New code would be:

```
def _zero_mean(input: Tensor,
               dim: int
               ) -> Tensor:
    from torch.linalg import norm
    return input - input.mean(dim=dim, keepdim=True) / norm(input, 'fro')
```

**Comment by brando90** [comment]
if you do change it let me know so I can pull the new version of anatome and make sure I don't divide by fro norm too many times.

**Comment by moskomule** [comment]
At least, CCA is invariant to affine transformation, meaning that division does not affect the distance. CKA is also scale-invariant.

**Comment by brando90** [comment]
> Both CCA and CKA are invariant to scale. Recently implemented Proc distance is internally rescaled.

ah so only OP needs the rescaling? weird why did the paper mentioned all of them required to have matrix A to be rescaled...?

**Comment by moskomule** [comment]
I guess it's for simplicity.
