### ISSUE TITLE
How do we run the jupyter notebook example?

### ISSUE THREAD

**Issue by brando90** [moskomule/anatome#17]
Got error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/brando/.torch/data/imagenet/val'
```

is it possible to download some data set to test anatome such that it doesn't throw an error?

Perhaps a colab example is better?

a start: https://colab.research.google.com/drive/1GrhWrWFPmlc6kmxc0TJY0Nb6qOBBgjzX?usp=sharing

**Comment by moskomule** [comment]
Just change the path in the following code to your favorite one.

```python
imagenet = ImageFolder('~/.torch/data/imagenet/val', 
                       transforms.Compose([transforms.CenterCrop(224),transforms.ToTensor(),
                       transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))]))
```

**Comment by brando90** [comment]
reproduce with this: https://colab.research.google.com/drive/1GrhWrWFPmlc6kmxc0TJY0Nb6qOBBgjzX?usp=sharing
